# Site settings
title: Mycelium-Network
email:
author:
description:
url: https://www.mycelium.space/
url_encoded: https%3A%2F%2Fwww.mycelium.space%2F
url_backend: https://mycelium.space/
api_endpoint: https://mycelium.space/

# Build settings
permalink: :title/
sass:
  sass_dir: css
